version: "3.9"

services:
    web:
        build: .
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        # command: gunicorn churugastos.wsgi:application --workers 3 --bind 0.0.0.0:8000
        ports:
            - "${PORT}:8000"
        volumes:
            - .:/app
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
        depends_on:
            - db

    db:
        image: postgres:16
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres_data:
