# Generated by Django 5.1.3 on 2024-11-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_last_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visited_project_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
