# Generated by Django 5.1.3 on 2024-11-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_last_visited_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_visited_project_id',
        ),
        migrations.AddField(
            model_name='user',
            name='last_visited_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_last_visited', to='api.project'),
        ),
    ]
