# Generated by Django 5.1.3 on 2024-12-20 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailynote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
